config/routes.rb
Rails.application.routes.draw do
  # get 'tags/index'
  # get 'albums/index'
  devise_for :users
  resources :users do
    resources :albums do
      resources :images do
        resources :tags
      end
    end
  end
  
  # get 'home/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "home#index"
  # root to: "albums#index"
end

app/models/album.rb
class Album < ApplicationRecord
    validates :title, presence: true
    validates :description, presence: true

    has_many :images, dependent: :destroy
    belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
  validates :image, presence: true
  validates :name, presence: true
  validates :all_tags, presence: true
  belongs_to :album
  has_one_attached :image
  has_many :taggings, dependent: :destroy
  has_many :tags , through: :taggings

  def pics
    return self.image.variant(resize: '295x280')
  end

  def all_tags=(names)
    self.tags = names.split(',').map do |name|
      Tag.where(name: name).first_or_create!
    end
  end
  def all_tags
    tags.map(&:name).join(", ")
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings ,dependent: :destroy
  has_many :images, through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :image
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :albums
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def index
    @user = User.find(current_user.id)
    @albums = @user.albums.all
    # @albums = Album.all
  end

  def show
    @user = User.find(current_user.id)
    @album = @user.albums.find_by_id(params[:id])
    # @album = Album.find(params[:id])
  end

  def new
    @album = Album.new
  end

  # def create
  #   @album = Album.new(album_params)

  #   if @album.save
  #     redirect_to albums_path
  #   else
  #     render :new
  #   end
  # end

  def create
    # debugger
    @user = User.find(current_user.id)
    @album = @user.albums.create(album_params)
    if @album.save
      redirect_to user_albums_path
    else
      render :new
    end
    # @album.save!
    # redirect_to user_albums_path
  end

  def edit
    # @user = User.find(current_user.id)
    # @album = @user.albums.find(params[:id])
    @album = Album.find(params[:id])
  end

  def update
    # @user = User.find(current_user.id)
    # @album = @user.albums.find(params[:id])
    @album = Album.find(params[:id])

    if @album.update(album_params)
      redirect_to user_albums_path
    else
      render :edit
    end
  end

  def destroy
    @album = Album.find(params[:id])
    @album.destroy
    redirect_to user_albums_path
  end

  private
    def album_params
      params.permit(:title, :description)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery

    def after_sign_in_path_for(user)
      origin_path = session[:origin_path]
      clear_origin_path
      if origin_path.present?
        origin_path
      else
        params[:target].presence || user_albums_path(user_id: current_user.id)
      end
    end
  
    private
  
    def authenticate_user!
      store_origin_path
      super
    end
  
    def store_origin_path
      session[:origin_path] = request.fullpath
    end
  
    def clear_origin_path
      session[:origin_path] = nil
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
    def new
        # @album = Album.find(params[:id])
        # @image = @album.images.new
        @image = Image.new
    end
    def create
        @album = Album.find(params[:album_id])
        @image = @album.images.create(image_params)
        if @image.save
            redirect_to user_album_path(id: @album.id)
        end
    end

    def destroy
        @album = Album.find(params[:id])
        @image = @album.images.find(params[:album_id])
        @image.destroy
        redirect_to user_album_path
    end


    private
    def image_params
        params.permit(:image, :name, :all_tags)
    end

end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/albums/_footer.html.erb
<div class="footer">
  <h2>&copy Manohar 2021</h2>
  <h2>Thank You</h2>
</div> 

app/views/albums/_popup.html.erb
<%# <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script> %>

<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js">                    
  $(document).ready(function(){
      $(".tagitem").click(function(){
        var imageid = $(this).attr("checkid");
          $("#exampleModalCenter").modal('show');
          $(".mytagform").attr('action', '/images/'+imageid+'/tags');
        });
      });
</script>    
                  
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        </div>
      <div class="modal-body">
      <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript">
        function onAddTag(tag) {
          alert("Added a tag: " + tag);
        }
        function onRemoveTag(tag) {
          alert("Removed a tag: " + tag);
        }

        function onChangeTag(input,tag) {
          alert("Changed a tag: " + tag);
        }

          // $("#mytagBtn").click(function(){
          //       var tagsArray = $("#tags_1").val();
          //         alert(tagsArray);
                
          // });
               
        $(function(){
            $('#tags_1').tagsInput({width:'auto'});                      
        });
        
      </script>
          <form  method="post" data-remote="true" class="mytagform">
        <p><label>Defaults:</label>
      <input name="tag_name" id="tags_1" type="text" class="tags" value="" /></p>
      <input type="submit" value="Save" data-disable-with="Save " />
      </form>
                      
      </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary" id="mytagBtn">Save changes</button>
      </div>                
    </div>
  </div>
</div>

 <button type="button" checkid="<%=@album.images%>" class="btn btn-primary btn-lg tagitem"  data-toggle="modal" >Preview</button>

app/views/albums/edit.html.erb
<h1 class="newalbum">Edit Albums</h1>

<%= form_with(url: user_album_path,method: "put") do |form| %>
  <div class="field">
      <div class="row">
        <div class="col-md-4 offset-4">
          <%= form.label :title %><br />
          <%= form.text_field :title, :class => 'form-control', :value => @album.try(:title) %>
          <% @album.errors.full_messages_for(:title).each do |message| %>
          <div id><%= message %></div>
          <% end %>
        </div>
      </div>
  </div>
  <div class="field">
      <div class="row">
        <div class="col-md-4 offset-4">
          <%= form.label :description %><br />
          <%= form.text_area :description, :class => 'form-control', :value => @album.try(:description) %>
          <% @album.errors.full_messages_for(:title).each do |message| %>
          <div><%= message %></div>
          <% end %>
        </div>
      </div>
  </div>
  <div>

  <div class="field">
    <div class="row">
      <div class="col-md-4 offset-4">
        <%= form.submit "Update", :class => 'btn btn-primary' %>
      </div>
    </div>
  </div>
<% end %>

app/views/albums/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Bootstrap CRUD Data Table for Database with Modal Form</title>
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto|Varela+Round">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
<style>
body {
	color: #566787;
	background: #f5f5f5;
	font-family: 'Varela Round', sans-serif;
	font-size: 13px;
}
.table-responsive {
    margin: 30px 0;
}
.table-wrapper {
	background: #fff;
	padding: 20px 25px;
	border-radius: 3px;
	min-width: 1000px;
	box-shadow: 0 1px 1px rgba(0,0,0,.05);
}
.table-title {        
	padding-bottom: 15px;
	background: #435d7d;
	color: #fff;
	padding: 16px 30px;
	min-width: 100%;
	margin: -20px -25px 10px;
	border-radius: 3px 3px 0 0;
}
.table-title h2 {
	margin: 5px 0 0;
	font-size: 24px;
}
.table-title .btn-group {
	float: right;
}
.table-title .btn {
	color: #fff;
	float: right;
	font-size: 13px;
	border: none;
	min-width: 50px;
	border-radius: 2px;
	border: none;
	outline: none !important;
	margin-left: 10px;
}
.table-title .btn i {
	float: left;
	font-size: 21px;
	margin-right: 5px;
}
.table-title .btn span {
	float: left;
	margin-top: 2px;
}
table.table tr th, table.table tr td {
	border-color: #e9e9e9;
	padding: 12px 15px;
	vertical-align: middle;
}
table.table tr th:first-child {
	width: 60px;
}
table.table tr th:last-child {
	width: 100px;
}
table.table-striped tbody tr:nth-of-type(odd) {
	background-color: #fcfcfc;
}
table.table-striped.table-hover tbody tr:hover {
	background: #f5f5f5;
}
table.table th i {
	font-size: 13px;
	margin: 0 5px;
	cursor: pointer;
}	
table.table td:last-child i {
	opacity: 0.9;
	font-size: 22px;
	margin: 0 5px;
}
table.table td a {
	font-weight: bold;
	color: #566787;
	display: inline-block;
	text-decoration: none;
	outline: none !important;
}
table.table td a:hover {
	color: #2196F3;
}
table.table td a.edit {
	color: #FFC107;
}
table.table td a.delete {
	color: #F44336;
}
table.table td i {
	font-size: 19px;
}
table.table .avatar {
	border-radius: 50%;
	vertical-align: middle;
	margin-right: 10px;
}
.pagination {
	float: right;
	margin: 0 0 5px;
}
.pagination li a {
	border: none;
	font-size: 13px;
	min-width: 30px;
	min-height: 30px;
	color: #999;
	margin: 0 2px;
	line-height: 30px;
	border-radius: 2px !important;
	text-align: center;
	padding: 0 6px;
}
.pagination li a:hover {
	color: #666;
}	
.pagination li.active a, .pagination li.active a.page-link {
	background: #03A9F4;
}
.pagination li.active a:hover {        
	background: #0397d6;
}
.pagination li.disabled i {
	color: #ccc;
}
.pagination li i {
	font-size: 16px;
	padding-top: 6px
}
.hint-text {
	float: left;
	margin-top: 10px;
	font-size: 13px;
}    
/* Custom checkbox */
.custom-checkbox {
	position: relative;
}
.custom-checkbox input[type="checkbox"] {    
	opacity: 0;
	position: absolute;
	margin: 5px 0 0 3px;
	z-index: 9;
}
.custom-checkbox label:before{
	width: 18px;
	height: 18px;
}
.custom-checkbox label:before {
	content: '';
	margin-right: 10px;
	display: inline-block;
	vertical-align: text-top;
	background: white;
	border: 1px solid #bbb;
	border-radius: 2px;
	box-sizing: border-box;
	z-index: 2;
}
.custom-checkbox input[type="checkbox"]:checked + label:after {
	content: '';
	position: absolute;
	left: 6px;
	top: 3px;
	width: 6px;
	height: 11px;
	border: solid #000;
	border-width: 0 3px 3px 0;
	transform: inherit;
	z-index: 3;
	transform: rotateZ(45deg);
}
.custom-checkbox input[type="checkbox"]:checked + label:before {
	border-color: #03A9F4;
	background: #03A9F4;
}
.custom-checkbox input[type="checkbox"]:checked + label:after {
	border-color: #fff;
}
.custom-checkbox input[type="checkbox"]:disabled + label:before {
	color: #b8b8b8;
	cursor: auto;
	box-shadow: none;
	background: #ddd;
}
/* Modal styles */
.modal .modal-dialog {
	max-width: 400px;
}
.modal .modal-header, .modal .modal-body, .modal .modal-footer {
	padding: 20px 30px;
}
.modal .modal-content {
	border-radius: 3px;
	font-size: 14px;
}
.modal .modal-footer {
	background: #ecf0f1;
	border-radius: 0 0 3px 3px;
}
.modal .modal-title {
	display: inline-block;
}
.modal .form-control {
	border-radius: 2px;
	box-shadow: none;
	border-color: #dddddd;
}
.modal textarea.form-control {
	resize: vertical;
}
.modal .btn {
	border-radius: 2px;
	min-width: 100px;
}	
.modal form label {
	font-weight: normal;
}	
h2.create-head{
  color: white;
  float: left
}
</style>
<script>
$(document).ready(function(){
	// Activate tooltip
	$('[data-toggle="tooltip"]').tooltip();
	
	// Select/Deselect checkboxes
	var checkbox = $('table tbody input[type="checkbox"]');
	$("#selectAll").click(function(){
		if(this.checked){
			checkbox.each(function(){
				this.checked = true;                        
			});
		} else{
			checkbox.each(function(){
				this.checked = false;                        
			});
		} 
	});
	checkbox.click(function(){
		if(!this.checked){
			$("#selectAll").prop("checked", false);
		}
	});
});
</script>
</head>
<body>
<div class="container-xl">
	<div class="table-responsive">
		<div class="table-wrapper">
			<div class="table-title">
				<div class="row">
					<div class="col-sm-6">
						<h2>My <b>Albums</b></h2>
					</div>
					<div class="col-sm-6">
						<h2 class="createalbum">
              <%= link_to "Create New Album",new_user_album_path(user_id: current_user.id), method: :get%>
            </h2>
						<h3>
            </h3>
					</div>
				</div>
			</div>
			<table class="table table-striped table-hover">
				<thead>
					<tr>
						<th>
							<span class="custom-checkbox">
								<input type="checkbox" id="selectAll">
								<label for="selectAll"></label>
							</span>
						</th>
						<th>Name</th>
						<th>Description</th>
            <th>Display</th>
						<th>Edit</th>
            <th>Delete</th>
					</tr>
				</thead>
				<tbody>
        <% @albums.each do |album| %>
					<tr>
						<td>
							<span class="custom-checkbox">
								<input type="checkbox" id="checkbox1" name="options[]" value="1">
								<label for="checkbox1"></label>
							</span>
						</td>
						<td><%= album.title %></td>
						<td><%= album.description %></td>
						<td><%= link_to "Show Album",user_album_path(album,user_id: current_user.id) %></td>
						<td><%= link_to "Edit Album",edit_user_album_path(album,user_id: current_user.id) %></td>
						<td><%= link_to "Delete Album",user_album_path(album,user_id: current_user.try(:id)),method: :delete, data: { confirm: "Are you sure?" } %></td>
					</tr>
        <%end%>
				</tbody>
			</table>
		</div>
	</div>        
</div>
<!-- Edit Modal HTML -->
<div id="addEmployeeModal" class="modal fade">
	<div class="modal-dialog">
		<div class="modal-content">
			<form>
				<div class="modal-header">						
					<h4 class="modal-title">Add Employee</h4>
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				</div>
				<div class="modal-body">					
					<div class="form-group">
						<label>Name</label>
						<input type="text" class="form-control" required>
					</div>
					<div class="form-group">
						<label>Email</label>
						<input type="email" class="form-control" required>
					</div>
					<div class="form-group">
						<label>Address</label>
						<textarea class="form-control" required></textarea>
					</div>
					<div class="form-group">
						<label>Phone</label>
						<input type="text" class="form-control" required>
					</div>					
				</div>
				<div class="modal-footer">
					<input type="button" class="btn btn-default" data-dismiss="modal" value="Cancel">
					<input type="submit" class="btn btn-success" value="Add">
				</div>
			</form>
		</div>
	</div>
</div>
<!-- Edit Modal HTML -->
<div id="editEmployeeModal" class="modal fade">
	<div class="modal-dialog">
		<div class="modal-content">
			<form>
				<div class="modal-header">						
					<h4 class="modal-title">Edit Employee</h4>
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				</div>
				<div class="modal-body">					
					<div class="form-group">
						<label>Name</label>
						<input type="text" class="form-control" required>
					</div>
					<div class="form-group">
						<label>Email</label>
						<input type="email" class="form-control" required>
					</div>
					<div class="form-group">
						<label>Address</label>
						<textarea class="form-control" required></textarea>
					</div>
					<div class="form-group">
						<label>Phone</label>
						<input type="text" class="form-control" required>
					</div>					
				</div>
				<div class="modal-footer">
					<input type="button" class="btn btn-default" data-dismiss="modal" value="Cancel">
					<input type="submit" class="btn btn-info" value="Save">
				</div>
			</form>
		</div>
	</div>
</div>
<!-- Delete Modal HTML -->
<div id="deleteEmployeeModal" class="modal fade">
	<div class="modal-dialog">
		<div class="modal-content">
			<form>
				<div class="modal-header">						
					<h4 class="modal-title">Delete Employee</h4>
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				</div>
				<div class="modal-body">					
					<p>Are you sure you want to delete these Records?</p>
					<p class="text-warning"><small>This action cannot be undone.</small></p>
				</div>
				<div class="modal-footer">
					<input type="button" class="btn btn-default" data-dismiss="modal" value="Cancel">
					<input type="submit" class="btn btn-danger" value="Delete">
				</div>
			</form>
		</div>
	</div>
</div>
</body>
</html>

app/views/albums/new.html.erb
<h1 class="newalbum">New Albums</h1>

<%= form_with url: user_albums_path do |form| %>
  <div class="field">
      <div class="row">
        <div class="col-md-4 offset-4">
          <%= form.label :title %><br />
          <%= form.text_field :title, :class => 'form-control' %>
          <% @album.errors.full_messages_for(:title).each do |message| %>
          <div id='msg'><%= message %></div>
          <% end %>
        </div>
      </div>
  </div>
  <div class="field">
      <div class="row">
        <div class="col-md-4 offset-4">
          <%= form.label :description %><br />
          <%= form.text_area :description, :class => 'form-control' %>
          <% @album.errors.full_messages_for(:description).each do |message| %>
          <div id='msg'><%= message %></div>
          <% end %>
        </div>
      </div>
  </div>
  <div>

  <div class="field">
    <div class="row">
      <div class="col-md-4 offset-4">
        <%= form.submit "Create", :class => 'btn btn-primary' %>
      </div>
    </div>
  </div>
<% end %>

app/views/albums/show.html.erb
<div class="showhead">
  <h2>Add a Photos</h2>
  <%= form_with url: user_album_images_path(album_id: @album.id)  do |form| %>
    <div class="field">
      <div class="row">
        <div class="col-md-4 offset-4">
          <%= form.label :image %><br />
          <%= form.file_field :image, :class => 'form-control' %> 
        </div>
      </div>
    </div>
    <div class="field">
      <div class="row">
        <div class="col-md-4 offset-4">
          <%= form.label :name %><br />
          <%= form.text_field :name, :class => 'form-control' %> 
        </div>
      </div>
    </div>
    <div class="field">
      <div class="row">
        <div class="col-md-4 offset-4">
          <%= form.label :Tags %><br />
          <%= form.text_field :all_tags, :class => 'form-control' %> 
        </div>
      </div>
    </div>
    <div class="field">
      <div class="row">
        <div class="col-md-4 offset-4">
          <%= form.submit "Save", :class => 'btn btn-primary' %>
        </div>
      </div>
    </div>
  <% end %>
</div>

<h2 id="phototitle"><%=@album.title%> Photos</h2>
<% @album.images.each do |photo| %>
  <div class="gallery">
    <% if photo.image.attached? %>
      <p>
        <%= image_tag(photo.pics)%>
      </p>
      <h4><%= photo.name%></h4>
      <h6><%= photo.all_tags%></h6>  
      <h5>
        <%= link_to "Delete",user_album_image_path(photo,user_id: current_user.id), :method => :delete,data: { confirm: "Are you sure?" } %>
      </h5>  
    <% end %> 
  </div>
<% end %>

app/views/home/index.html.erb
<% name = current_user.present? ? current_user.email : '' %>

<h2 class="emailhead">Welcome <%= name %> </h2>

<% if current_user.present? %>
    <h1 class="newalbum"><%= link_to "Dashboard", user_albums_path(user_id: current_user.try(:id)) %></h1>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlbumApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/shared/_form.html.erb
<div class="container-fluid px-1 px-md-5 px-lg-1 px-xl-5 py-5 mx-auto">
    <div class="card card0 border-0">
        <div class="row d-flex">
            <div class="col-lg-6">
                <div class="card1 pb-5">
                    <div class="row"> <img src="https://i.imgur.com/CXQmsmF.png" class="logo"> </div>
                    <div class="row px-3 justify-content-center mt-4 mb-5 border-line"> <img src="https://i.imgur.com/uNGdWHi.png" class="image"> </div>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="card2 card border-0 px-4 py-5">
                    <div class="row mb-4 px-3">
                        <h6 class="mb-0 mr-4 mt-2">Sign in with</h6>
                        <div class="facebook text-center mr-3">
                            <div class="fa fa-facebook"></div>
                        </div>
                        <div class="twitter text-center mr-3">
                            <div class="fa fa-twitter"></div>
                        </div>
                        <div class="linkedin text-center mr-3">
                            <div class="fa fa-linkedin"></div>
                        </div>
                    </div>
                    <div class="row px-3 mb-4">
                        <div class="line"></div> <small class="or text-center">Or</small>
                        <div class="line"></div>
                    </div>
                    <div class="row px-3"> <label class="mb-1">
                            <h6 class="mb-0 text-sm">Email Address</h6>
                        </label> <input class="mb-4" type="text" name="email" placeholder="Enter a valid email address"> </div>
                    <div class="row px-3"> <label class="mb-1">
                            <h6 class="mb-0 text-sm">Password</h6>
                        </label> <input type="password" name="password" placeholder="Enter password"> </div>
                    <div class="row px-3 mb-4">
                        <div class="custom-control custom-checkbox custom-control-inline"> <input id="chk1" type="checkbox" name="chk" class="custom-control-input"> <label for="chk1" class="custom-control-label text-sm">Remember me</label> </div> <a href="#" class="ml-auto mb-0 text-sm">Forgot Password?</a>
                    </div>
                    <div class="row mb-3 px-3"> <button type="submit" class="btn btn-blue text-center">Login</button> </div>
                    <div class="row mb-4 px-3"> <small class="font-weight-bold">Don't have an account? <a class="text-danger ">Register</a></small> </div>
                </div>
            </div>
        </div>
        <div class="bg-blue py-4">
            <div class="row px-3"> <small class="ml-4 ml-sm-5 mb-2">Copyright &copy; 2019. All rights reserved.</small>
                <div class="social-contact ml-4 ml-sm-auto"> <span class="fa fa-facebook mr-4 text-sm"></span> <span class="fa fa-google-plus mr-4 text-sm"></span> <span class="fa fa-linkedin mr-4 text-sm"></span> <span class="fa fa-twitter mr-4 mr-sm-5 text-sm"></span> </div>
            </div>
        </div>
    </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">Album App</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
            <li class="nav-item">
                <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
            </li>
        <% else %>
            <li class="nav-item">
                <%= link_to 'Sign In', new_user_session_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
                <%= link_to 'Register', new_user_registration_path, class: 'nav-link' %>
            </li>
        <% end %>
    </ul>
  </div>
</nav>

app/views/tags/index.html.erb
<h1>Tags#index</h1>
<p>Find me in app/views/tags/index.html.erb</p>

app/views/tags/new.html.erb
<%= render 'albums/form' %>

app/views/tags/show.html.erb
<% @image.tags.each do |tag| %>
  <%= tag.tag %> 
<% end %>